//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmaciaAEntities : DbContext
    {
        public FarmaciaAEntities()
            : base("name=FarmaciaAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<LABORATORIO> LABORATORIO { get; set; }
        public DbSet<PRESENTACION> PRESENTACION { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
        public DbSet<SUCURSAL_PRODUCTO> SUCURSAL_PRODUCTO { get; set; }
        public DbSet<t_oauthtoken> t_oauthtoken { get; set; }
        public DbSet<FARMACIA> FARMACIA { get; set; }
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
