//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaciaA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public SUCURSAL()
        {
            this.SUCURSAL_PRODUCTO = new HashSet<SUCURSAL_PRODUCTO>();
        }
    
        public int ID_SUCURSAL { get; set; }
        public string SUCURSAL1 { get; set; }
        public string DIRECCION { get; set; }
        public string LONGITUD { get; set; }
        public string LATITUD { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual ICollection<SUCURSAL_PRODUCTO> SUCURSAL_PRODUCTO { get; set; }
    }
}
